// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADa446iN2u-AGk_nDRs5C3xl5BBtv5xc0',
    appId: '1:1060223180685:web:8dc884198b047e883ee7c4',
    messagingSenderId: '1060223180685',
    projectId: 'studenty-e9063',
    authDomain: 'studenty-e9063.firebaseapp.com',
    storageBucket: 'studenty-e9063.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDho8WPvBNB1dTAh7F0KBB4e51FeIqy3Hs',
    appId: '1:1060223180685:android:85e776291e22bc7c3ee7c4',
    messagingSenderId: '1060223180685',
    projectId: 'studenty-e9063',
    storageBucket: 'studenty-e9063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBozTFGa1bKrX1ZG8CuYiK5MkbcE64cxbk',
    appId: '1:1060223180685:ios:d0f074c26998013b3ee7c4',
    messagingSenderId: '1060223180685',
    projectId: 'studenty-e9063',
    storageBucket: 'studenty-e9063.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBozTFGa1bKrX1ZG8CuYiK5MkbcE64cxbk',
    appId: '1:1060223180685:ios:9a27b5df4f2d6b463ee7c4',
    messagingSenderId: '1060223180685',
    projectId: 'studenty-e9063',
    storageBucket: 'studenty-e9063.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
